### ISSUE TITLE
Feature Request: Navigate with keyboard

### ISSUE THREAD

**Issue by MichaelChirico** [BansheeMediaPlayer/BansheeMediaPlayer.github.io#7]
As an iTunes veteran, the mapping of shortcuts directly to keyboard keys (as opposed to tied through chooser keys like shift or control) is a major bugbear.

The requirement to enter the search bar to navigate quickly is cumbersome--in the situation where I'm jonesing for a particular track, but would like the shuffle of my full library to ensue, the need to remember to X out of the search selection seems unnecessary.

**Comment by bl8** [comment]
Hello,

This GitHub repository, and the associated issue tracker, are only for the http://banshee.fm web siote itself.
Please file your issues or suggestion for Banshee as described at http://banshee.fm/contribute/
