### ISSUE TITLE
Feature Request: On-the-fly `up next` management for dynamic playlists, especially while on shuffle

### ISSUE THREAD

**Issue by MichaelChirico** [BansheeMediaPlayer/BansheeMediaPlayer.github.io#8]
I would love to have a tool for dynamically interacting with the upcoming tracks, especially while playing on shuffle (one of the few things I miss about iTunes).

Basically, have an interface for seeing / modifying the next 10 songs to play, including functionalities for:

 1. deleting upcoming songs (great on shuffle, when you're in the mood for some songs, but you just don't know which yet)
 2. playing an album / set of user-defined songs before returning to shuffle/pre-assignment status quo
 3. curtailing future play with something like a Clear option which would allow Banshee to keep playing, but not indefinitely, when I leave the computer

**Comment by bl8** [comment]
Hello,

This GitHub repository, and the associated issue tracker, are only for the http://banshee.fm web site itself.
Please file your issues or suggestion for Banshee as described at http://banshee.fm/contribute/

**Comment by MichaelChirico** [comment]
Thanks, sorry for the confusion
